/**
 * Tool-count consistency test — Round-1 audit I8 fix.
 *
 * Pins the documented numbers across README.md, SKILL.md, manifest.json,
 * and install-skill.ts so silent drift between docs and code is caught
 * at test-time rather than after publish.
 *
 * **The canonical truth model:**
 *   - **24 domain tools** registered by `buildAllTools()` (the tool
 *     catalogue surface).
 *   - **1 gateway tool** (`yootheme_builder_advanced`) registered
 *     additionally by `registerAdvancedTool()`.
 *   - **25 tools total** dispatchable end-to-end (23 + gateway).
 *   - **17 entries in `tools.list`** (8 essential forwarded + 2 direct
 *     top-level + 1 gateway), keeping us well under the Cursor
 *     ≤ ~40-tool cap even when the catalogue grows.
 *
 * This test re-derives the 23 / 24 / 11 numbers from `buildAllTools`,
 * `ESSENTIAL_TOOLS`, and `DIRECT_TOP_LEVEL_TOOLS` so it adapts when
 * the registry changes, but enforces the SAME consistent vocabulary
 * across every human-facing artifact.
 *
 * @license MIT
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { RestClient } from '../../src/client.js';
import {
    DIRECT_TOP_LEVEL_TOOLS,
    ESSENTIAL_TOOLS,
} from '../../src/gateway/essentials.js';
import { buildAllTools } from '../../src/tools/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..', '..');

const DOMAIN_TOOL_COUNT = buildAllTools(
    new RestClient({ baseUrl: 'https://example.com', bearerToken: 't' }),
).length;
const TOTAL_TOOL_COUNT = DOMAIN_TOOL_COUNT + 1; // + the gateway
const TOOLS_LIST_COUNT =
    ESSENTIAL_TOOLS.length + DIRECT_TOP_LEVEL_TOOLS.length + 1; // + gateway

function readFile(rel: string): string {
    const path = resolve(PKG_ROOT, rel);
    expect(existsSync(path), `expected ${rel} to exist`).toBe(true);
    return readFileSync(path, 'utf-8');
}

describe('tool-count consistency (Round-1 audit I8)', () => {
    it('exposes 24 domain tools (sanity check on the registry itself)', () => {
        expect(DOMAIN_TOOL_COUNT).toBe(24);
    });

    it('exposes 17 entries in tools.list (8 essential + 2 direct + 1 gateway)', () => {
        expect(TOOLS_LIST_COUNT).toBe(17);
    });

    it('totals 25 tools end-to-end (24 domain + 1 gateway)', () => {
        expect(TOTAL_TOOL_COUNT).toBe(25);
    });

    it('README mentions a domain-tool catalogue count', () => {
        const text = readFile('README.md');
        // The README cites a tool count; accept any 2-digit count so the
        // pin survives catalogue growth without churn.
        expect(text).toMatch(/\b\d{2}\b\s+(domain\s+)?tool/i);
    });

    it('README clarifies the gateway tools/list model', () => {
        const text = readFile('README.md');
        // The README must clarify the gateway model so users understand
        // why their AI client only "sees" a reduced tools/list surface.
        expect(text.toLowerCase()).toContain('gateway');
    });

    it('SKILL.md prose mentions the total tool surface', () => {
        const text = readFile('skills/yootheme-builder/SKILL.md');
        expect(text).toMatch(/\b\d{2}\b\s*(typed|MCP|tools)/);
    });

    it('SKILL.md appendix declares the 24-tool count (auto-generated)', () => {
        const text = readFile('skills/yootheme-builder/SKILL.md');
        // The appendix's "**N tools** — generated by …" header reflects
        // the domain-registry count (without the gateway).
        expect(text).toMatch(/\*\*24 tools\*\*/);
    });

    it('install-skill.ts marker block mentions 24 tools', () => {
        const text = readFile('src/install-skill.ts');
        expect(text).toMatch(/\b24\b\s*MCP\s*tools/);
    });
});
