/**
 * Tool-count consistency test — Round-1 audit I8 fix.
 *
 * Pins the documented numbers across README.md, SKILL.md, manifest.json,
 * and install-skill.ts so silent drift between docs and code is caught
 * at test-time rather than after publish.
 *
 * **The canonical truth model:**
 *   - **21 domain tools** registered by `buildAllTools()` (the tool
 *     catalogue surface).
 *   - **1 gateway tool** (`yootheme_builder_advanced`) registered
 *     additionally by `registerAdvancedTool()`.
 *   - **22 tools total** dispatchable end-to-end (21 + gateway).
 *   - **10 entries in `tools/list`** (7 essential forwarded + 2 direct
 *     top-level + 1 gateway), keeping us well under the Cursor
 *     ≤ ~40-tool cap even when the catalogue grows.
 *
 * This test re-derives the 21 / 22 / 10 numbers from `buildAllTools`,
 * `ESSENTIAL_TOOLS`, and `DIRECT_TOP_LEVEL_TOOLS` so it adapts when
 * the registry changes, but enforces the SAME consistent vocabulary
 * across every human-facing artifact.
 *
 * @license MIT
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { RestClient } from '../../src/client.js';
import {
    DIRECT_TOP_LEVEL_TOOLS,
    ESSENTIAL_TOOLS,
} from '../../src/gateway/essentials.js';
import { buildAllTools } from '../../src/tools/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..', '..');

const DOMAIN_TOOL_COUNT = buildAllTools(
    new RestClient({ baseUrl: 'https://example.com', bearerToken: 't' }),
).length;
const TOTAL_TOOL_COUNT = DOMAIN_TOOL_COUNT + 1; // + the gateway
const TOOLS_LIST_COUNT =
    ESSENTIAL_TOOLS.length + DIRECT_TOP_LEVEL_TOOLS.length + 1; // + gateway

function readFile(rel: string): string {
    const path = resolve(PKG_ROOT, rel);
    expect(existsSync(path), `expected ${rel} to exist`).toBe(true);
    return readFileSync(path, 'utf-8');
}

describe('tool-count consistency (Round-1 audit I8)', () => {
    it('exposes 21 domain tools (sanity check on the registry itself)', () => {
        expect(DOMAIN_TOOL_COUNT).toBe(21);
    });

    it('exposes 10 entries in tools/list (7 essential + 2 direct + 1 gateway)', () => {
        expect(TOOLS_LIST_COUNT).toBe(10);
    });

    it('totals 22 tools end-to-end (21 domain + 1 gateway)', () => {
        expect(TOTAL_TOOL_COUNT).toBe(22);
    });

    it('README mentions the 21-tool domain catalogue', () => {
        const text = readFile('README.md');
        // Allow either "21 tool" or "21 domain tool" wording so the
        // pin-test is robust to phrasing tweaks.
        expect(text).toMatch(/\b21\b\s+(domain\s+)?tool/i);
    });

    it('README mentions the 10 tools/list entries (gateway-model)', () => {
        const text = readFile('README.md');
        // The README must clarify the gateway model so users
        // understand why their AI client only "sees" 10 tools.
        expect(text).toMatch(/\b10\b/);
    });

    it('SKILL.md prose mentions 22 tools (total surface, incl. gateway)', () => {
        const text = readFile('skills/yootheme-builder/SKILL.md');
        expect(text).toMatch(/\b22\b\s*(typed|MCP|tools)/);
    });

    it('SKILL.md appendix declares the 21-tool count (auto-generated)', () => {
        const text = readFile('skills/yootheme-builder/SKILL.md');
        // The appendix's "**N tools** — generated by …" header reflects
        // the domain-registry count (without the gateway).
        expect(text).toMatch(/\*\*21 tools\*\*/);
    });

    it('install-skill.ts marker block mentions 22 tools', () => {
        const text = readFile('src/install-skill.ts');
        expect(text).toMatch(/\b22\b\s*MCP\s*tools/);
    });
});
