/**
 * Error-code taxonomy + AI-friendly hint messages.
 *
 * `classify(status)` maps the HTTP status of a failed REST call into one
 * of nine canonical `YtbErrorCode` values. `hintFor(code)` returns a
 * recovery-oriented hint string the LLM can act on without re-reading the
 * raw error message.
 *
 * Centralising the taxonomy means every tool's catch-block emits the
 * same vocabulary, and the audit gate can pin the exact set of hints
 * that ship.
 *
 * Reference: `apimapper-mcp/src/modules/apimapper/client.ts:hintFor`
 * (Wave G.6.1 — same shape, ported for the YOOtheme Builder REST API).
 *
 * @license MIT
 */

/**
 * Canonical YOOtheme-Builder-MCP error code union.
 *
 * Order is documentary only — `classify()` returns whichever applies.
 */
export type YtbErrorCode =
    | 'auth_invalid' // 401 with WWW-Authenticate (key rejected)
    | 'auth_missing' // 401 without WWW-Authenticate (no bearer sent)
    | 'forbidden' // 403 (scope insufficient)
    | 'not_found' // 404
    | 'conflict_etag' // 409 / 412 (optimistic-lock failure)
    | 'validation_error' // 422 (body schema rejected)
    | 'rate_limit' // 429
    | 'server_error' // 5xx + 2xx fallback (caller misuse)
    | 'network'; // status 0 / fetch threw

/** Options for `classify()` — second-tier signals (e.g. response headers). */
export interface ClassifyOptions {
    /**
     * Whether the response carried a `WWW-Authenticate` header. Used to
     * distinguish `auth_missing` (no bearer sent → server didn't ask for one
     * via WWW-Authenticate; misconfigured client) from `auth_invalid`
     * (server rejected the bearer that WAS sent).
     */
    readonly hasWwwAuthenticate?: boolean;
}

/**
 * Map an HTTP status into a `YtbErrorCode`.
 *
 * Special-cases:
 *   - 401 with `hasWwwAuthenticate: false` → `auth_missing`
 *   - 401 with `hasWwwAuthenticate: true`  → `auth_invalid` (default)
 *   - 412 (Precondition Failed) is treated as `conflict_etag` alongside 409.
 *   - Status 0 (no response) → `network`.
 *   - Anything we don't recognise (incl. 2xx) → `server_error` so the agent
 *     sees a non-empty hint rather than silently swallowing.
 */
export function classify(status: number, options: ClassifyOptions = {}): YtbErrorCode {
    if (status === 0) return 'network';
    if (status === 401) {
        return options.hasWwwAuthenticate === false ? 'auth_missing' : 'auth_invalid';
    }
    if (status === 403) return 'forbidden';
    if (status === 404) return 'not_found';
    if (status === 409 || status === 412) return 'conflict_etag';
    if (status === 422) return 'validation_error';
    if (status === 429) return 'rate_limit';
    if (status >= 500) return 'server_error';
    return 'server_error';
}

/**
 * Return a focused hint describing how the agent (or the user) can
 * recover from a given error code. Always non-empty.
 */
export function hintFor(code: YtbErrorCode): string {
    switch (code) {
        case 'auth_invalid':
            return (
                'Bearer key rejected (HTTP 401, key signature invalid or revoked). ' +
                'Open wp-admin → "YOOtheme Builder MCP" → Settings, regenerate the ' +
                'key, and update YTB_MCP_BEARER_TOKEN in your AI-client config. ' +
                'Then restart the client.'
            );
        case 'auth_missing':
            return (
                'No Bearer credential sent (HTTP 401 without WWW-Authenticate echo). ' +
                'Set the YTB_MCP_BEARER_TOKEN environment variable in your AI-client ' +
                'MCP configuration to a key generated by the plugin Settings page.'
            );
        case 'forbidden':
            return (
                'Permission denied (HTTP 403). Your Bearer key lacks the required ' +
                'scope for this operation. Regenerate a key with the correct ' +
                'scope (read / write / admin) in the plugin Settings page.'
            );
        case 'not_found':
            return (
                'Resource not found (HTTP 404). Use the matching `*_list` tool ' +
                '(yootheme_builder_pages_list, yootheme_builder_element_list, …) ' +
                'to discover valid IDs / paths. IDs are case-sensitive.'
            );
        case 'conflict_etag':
            return (
                'Optimistic-lock failed (HTTP 409/412). Another writer changed ' +
                'the state since you fetched it. Call yootheme_builder_get_etag ' +
                'again to get the fresh ETag, then retry your write with that ETag.'
            );
        case 'validation_error':
            return (
                'Request body failed validation (HTTP 422). Re-check the tool\'s ' +
                'inputSchema and the element-type schema via ' +
                'yootheme_builder_element_type_get_schema for valid `props` keys.'
            );
        case 'rate_limit':
            return (
                'Rate limit reached (HTTP 429). This is likely Cloudflare or ' +
                'another WAF in front of WordPress, not the plugin itself. Wait ' +
                'a few seconds and retry. If persistent, check the WAF rate-limit ' +
                'rule in your Cloudflare dashboard.'
            );
        case 'server_error':
            return (
                'Upstream server error (HTTP 5xx or unexpected status). Retry ' +
                'after a short delay; if it persists, check the WordPress error ' +
                'log (wp-content/debug.log) for the underlying PHP exception.'
            );
        case 'network':
            return (
                'Network or timeout error reaching WordPress. Verify ' +
                'YTB_MCP_WP_URL is correct and reachable from this host (try ' +
                '`curl <YTB_MCP_WP_URL>/wp-json/yt-builder-mcp/v1/health`).'
            );
    }
}
