<?php
/**
 * LayoutReader — read-only window into wp_option('yootheme').
 *
 * Spike-Outcomes (2026-05-21) confirmed that YOOtheme Pro persists its
 * entire Builder state — `library` + `templates` map — as a single JSON
 * blob in `wp_option('yootheme')`. This class is the canonical read
 * path for every Wave 2+ tool that wants to inspect the tree.
 *
 * It deliberately bypasses `Builder::load()`: Spike-3 verified that the
 * stored JSON is already normalized (the load-time transforms run only
 * for context='save' / context='render', not for context='read'). Going
 * through `update_option`-backed PHP load is therefore unnecessary
 * overhead for read paths.
 *
 * The class never mutates state — every method is idempotent and free of
 * side-effects. Writes belong to Wave 3.
 *
 * @license GPL-2.0-or-later
 * @package WootsUp\BuilderMcp\State
 */

declare(strict_types=1);

namespace WootsUp\BuilderMcp\State;

final class LayoutReader implements LayoutReaderInterface
{
    /** wp_option key per spike-outcomes. */
    public const OPTION = 'yootheme';

    private readonly StateRevisionInterface $revision;

    public function __construct(?StateRevisionInterface $revision = null)
    {
        $this->revision = $revision ?? new StateRevision();
    }

    /**
     * Return the entire builder state — `library` + `templates` top-level
     * keys — as an associative array. Returns the empty array if the
     * option is missing or corrupt (defensive: if some other plugin
     * clobbered `wp_option('yootheme')` we must not blow up).
     *
     * @return array<string, mixed>
     */
    public function read(): array
    {
        /** @var mixed $raw */
        $raw = \get_option(self::OPTION, []);

        if (is_string($raw)) {
            // Some YT versions persist the option as a JSON string instead
            // of a serialized PHP array. Decode lazily and fall back to []
            // on parse failure.
            $decoded = json_decode($raw, true);
            if (is_array($decoded)) {
                return $decoded;
            }
            return [];
        }

        if (!is_array($raw)) {
            return [];
        }

        return $raw;
    }

    /**
     * Return the JSON tree for a single template (top-level key under
     * `templates.<id>` in the wp_option), or null if the template is
     * unknown.
     *
     * @return array<string, mixed>|null
     */
    public function readTemplate(string $templateId): ?array
    {
        $state = $this->read();
        if (!isset($state['templates']) || !is_array($state['templates'])) {
            return null;
        }
        /** @var array<string, mixed> $templates */
        $templates = $state['templates'];
        if (!isset($templates[$templateId]) || !is_array($templates[$templateId])) {
            return null;
        }
        /** @var array<string, mixed> $template */
        $template = $templates[$templateId];
        return $template;
    }

    /**
     * Return the list of template-IDs (top-level keys of `templates`).
     *
     * Spike-2: template-IDs are 8-character base64-style strings
     * (e.g. `bFIb-syj`, `Fp2ntvJd`) auto-generated by the Builder.
     *
     * @return list<string>
     */
    public function listTemplateIds(): array
    {
        $state = $this->read();
        if (!isset($state['templates']) || !is_array($state['templates'])) {
            return [];
        }
        /** @var array<string, mixed> $templates */
        $templates = $state['templates'];
        $ids = [];
        foreach (array_keys($templates) as $key) {
            $ids[] = (string) $key;
        }
        return $ids;
    }

    /**
     * Compute a deterministic ETag for the current state.
     *
     * Format: `<sha256-of-state>-r<revision>`. The revision component is
     * the monotonic counter maintained by {@see StateRevision} and bumped
     * on every persisted mutation by LayoutWriter::persist(). This is the
     * F-07 fix (Maria-Audit 2026-05-22): a pure content hash is
     * ABA-vulnerable — `add → delete` collapses to the original state, so
     * the second ETag equals the first and clients can lose intermediate
     * progress on optimistic-lock writes. Appending the monotonic
     * revision makes every committed mutation surface as a distinct ETag.
     *
     * Spike-5 settled that we'll use this for optimistic-lock conflict
     * detection on Wave-3 writes (`If-Match: <etag>` header).
     */
    public function etag(): string
    {
        $state = $this->read();
        // json_encode is canonical-enough for our purposes (PHP preserves
        // insertion order on assoc-arrays since 7.x). If a user-side YT
        // save reorders keys, a different ETag is the correct outcome —
        // it correctly signals "something changed".
        $encoded = json_encode($state, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        $hash = $encoded === false ? hash('sha256', '') : hash('sha256', $encoded);
        return $hash . '-r' . (string) $this->revision->current();
    }

    /**
     * Return the underlying StateRevision tracker. Exposed so writers
     * (LayoutWriter::persist) can bump it inside their critical section.
     */
    public function getRevision(): StateRevisionInterface
    {
        return $this->revision;
    }

    /**
     * Resolve a JSON-Pointer (RFC-6901) against the full builder state.
     *
     * Convenience wrapper that calls {@see JsonPointer::get} on the read
     * snapshot. Returns null for missing paths; throws
     * InvalidArgumentException on structurally-invalid pointers.
     */
    public function readByPointer(string $pointer): mixed
    {
        return JsonPointer::get($this->read(), $pointer);
    }
}
