/**
 * Tests for `auth.ts` — env-driven config loader.
 *
 * @license MIT
 */

import { describe, expect, it } from 'vitest';

import {
    ENV_BEARER,
    ENV_PLATFORM,
    ENV_SITE_URL,
    ENV_TEST_MODE,
    ENV_TIMEOUT,
    ENV_WP_URL,
    isTestMode,
    loadConfig,
} from '../src/auth.js';
import { ConfigError } from '../src/errors.js';

// Realistic Bearer test fixtures — match the production format
// generated by `KeyService.php` (`ytb_live_<payloadB64Url>.<sigB64Url>`).
// Round-1 audit I7 fix: client-side `loadConfig` now performs a Zod
// regex check, so test fixtures must use the real shape.
const VALID_BEARER_LIVE =
    'ytb_live_eyJraWQiOiJ0ZXN0LWtleSIsInNjb3BlIjoid3JpdGUifQ.abc123_xyz-def';
const VALID_BEARER_TEST =
    'ytb_test_eyJraWQiOiJ0LWtleSIsInNjb3BlIjoicmVhZCJ9.qrs456_uvw-mno';

describe('loadConfig', () => {
    it('returns a normalised config when both env vars are set', () => {
        const cfg = loadConfig({
            env: {
                [ENV_WP_URL]: 'https://example.com/',
                [ENV_BEARER]: VALID_BEARER_LIVE,
            },
        });
        expect(cfg.baseUrl).toBe('https://example.com');
        expect(cfg.bearerToken).toBe(VALID_BEARER_LIVE);
        expect(cfg.timeoutMs).toBe(15_000);
    });

    it('strips trailing slashes from the base URL', () => {
        const cfg = loadConfig({
            env: {
                [ENV_WP_URL]: 'https://example.com////',
                [ENV_BEARER]: VALID_BEARER_LIVE,
            },
        });
        expect(cfg.baseUrl).toBe('https://example.com');
    });

    it('throws ConfigError when URL is missing', () => {
        expect(() => loadConfig({ env: { [ENV_BEARER]: VALID_BEARER_LIVE } })).toThrowError(ConfigError);
    });

    it('throws ConfigError when bearer is missing (default)', () => {
        expect(() =>
            loadConfig({ env: { [ENV_WP_URL]: 'https://example.com' } }),
        ).toThrowError(ConfigError);
    });

    it('allows missing bearer when allowMissingToken=true', () => {
        const cfg = loadConfig({
            env: { [ENV_WP_URL]: 'https://example.com' },
            allowMissingToken: true,
        });
        expect(cfg.bearerToken).toBe('');
    });

    it('parses custom timeout from env', () => {
        const cfg = loadConfig({
            env: {
                [ENV_WP_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
                [ENV_TIMEOUT]: '5000',
            },
        });
        expect(cfg.timeoutMs).toBe(5000);
    });

    it('falls back to default timeout on invalid value', () => {
        const cfg = loadConfig({
            env: {
                [ENV_WP_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
                [ENV_TIMEOUT]: 'not-a-number',
            },
        });
        expect(cfg.timeoutMs).toBe(15_000);
    });

    // Round-1 audit I7 fix: client-side Bearer format check
    // (matches the `ytb_live_<payloadB64Url>.<sigB64Url>` shape
    // emitted by `KeyService.php:PREFIX=ytb_live_` + base64url payload
    // and signature). Fail-fast before the client makes any request
    // with a garbage token.
    describe('Bearer format check (I7)', () => {
        it('accepts a well-formed ytb_live_ bearer', () => {
            const cfg = loadConfig({
                env: {
                    [ENV_WP_URL]: 'https://example.com',
                    [ENV_BEARER]: VALID_BEARER_LIVE,
                },
            });
            expect(cfg.bearerToken).toBe(VALID_BEARER_LIVE);
        });

        it('accepts a well-formed ytb_test_ bearer', () => {
            const cfg = loadConfig({
                env: {
                    [ENV_WP_URL]: 'https://example.com',
                    [ENV_BEARER]: VALID_BEARER_TEST,
                },
            });
            expect(cfg.bearerToken).toBe(VALID_BEARER_TEST);
        });

        it('rejects a token without the ytb_live_ / ytb_test_ prefix', () => {
            expect(() =>
                loadConfig({
                    env: {
                        [ENV_WP_URL]: 'https://example.com',
                        [ENV_BEARER]: 'tok_abc123',
                    },
                }),
            ).toThrowError(/Bearer.*format|ytb_(live|test)_/);
        });

        it('rejects a token missing the payload.sig separator', () => {
            expect(() =>
                loadConfig({
                    env: {
                        [ENV_WP_URL]: 'https://example.com',
                        [ENV_BEARER]: 'ytb_live_nodotseparator',
                    },
                }),
            ).toThrowError(/Bearer.*format|ytb_(live|test)_/);
        });

        it('rejects a token that pastes the `Bearer ` prefix into the env var (common mistake)', () => {
            expect(() =>
                loadConfig({
                    env: {
                        [ENV_WP_URL]: 'https://example.com',
                        [ENV_BEARER]: `Bearer ${VALID_BEARER_LIVE}`,
                    },
                }),
            ).toThrowError(/Bearer.*format|ytb_(live|test)_/);
        });

        it('rejects an absurdly long token (defense-in-depth bound)', () => {
            const tooLong =
                'ytb_live_' + 'A'.repeat(600) + '.' + 'B'.repeat(600);
            expect(() =>
                loadConfig({
                    env: {
                        [ENV_WP_URL]: 'https://example.com',
                        [ENV_BEARER]: tooLong,
                    },
                }),
            ).toThrowError(/too long|max|512/i);
        });

        it('still rejects empty bearer with the original ConfigError (precondition before format check)', () => {
            expect(() =>
                loadConfig({
                    env: {
                        [ENV_WP_URL]: 'https://example.com',
                        [ENV_BEARER]: '',
                    },
                }),
            ).toThrowError(/Missing YTB_MCP_BEARER_TOKEN/);
        });
    });
});

// ── Wave 7 — YTB_MCP_SITE_URL + YTB_MCP_PLATFORM ────────────────────
describe('loadConfig — Wave 7 platform-agnostic env vars', () => {
    it('prefers YTB_MCP_SITE_URL over YTB_MCP_WP_URL when both are set', () => {
        const cfg = loadConfig({
            env: {
                [ENV_SITE_URL]: 'https://site.example.com',
                [ENV_WP_URL]: 'https://legacy.example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
            },
        });
        expect(cfg.baseUrl).toBe('https://site.example.com');
    });

    it('falls back to YTB_MCP_WP_URL when only the legacy var is set', () => {
        const cfg = loadConfig({
            env: {
                [ENV_WP_URL]: 'https://legacy.example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
            },
        });
        expect(cfg.baseUrl).toBe('https://legacy.example.com');
    });

    it('parses YTB_MCP_PLATFORM=joomla into platformHint', () => {
        const cfg = loadConfig({
            env: {
                [ENV_SITE_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
                [ENV_PLATFORM]: 'joomla',
            },
        });
        expect(cfg.platformHint).toBe('joomla');
    });

    it('parses YTB_MCP_PLATFORM=wordpress into platformHint', () => {
        const cfg = loadConfig({
            env: {
                [ENV_SITE_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
                [ENV_PLATFORM]: 'wordpress',
            },
        });
        expect(cfg.platformHint).toBe('wordpress');
    });

    it('ignores YTB_MCP_PLATFORM with an unrecognised value (no hint set)', () => {
        const cfg = loadConfig({
            env: {
                [ENV_SITE_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
                [ENV_PLATFORM]: 'drupal',
            },
        });
        expect(cfg.platformHint).toBeUndefined();
    });

    it('platformHint is undefined when YTB_MCP_PLATFORM is not set', () => {
        const cfg = loadConfig({
            env: {
                [ENV_SITE_URL]: 'https://example.com',
                [ENV_BEARER]: VALID_BEARER_LIVE,
            },
        });
        expect(cfg.platformHint).toBeUndefined();
    });
});

describe('isTestMode', () => {
    it('returns true when YTB_MCP_TEST_MODE=1', () => {
        expect(isTestMode({ [ENV_TEST_MODE]: '1' })).toBe(true);
    });

    it('returns false otherwise', () => {
        expect(isTestMode({})).toBe(false);
        expect(isTestMode({ [ENV_TEST_MODE]: '0' })).toBe(false);
    });
});
