#!/usr/bin/env node
/**
 * scripts/extract-tools.mjs — Wave G.7.6.
 *
 * Loads the compiled tool registry from `dist/`, extracts the metadata
 * agents need (name, description, input keys, annotations) and emits a
 * deterministic Markdown table. The output is consumed by:
 *
 *   1. `skills/yootheme-builder/SKILL.md`   — appended as the "Tool
 *      Catalog" appendix (so the skill is auto-kept-in-sync with the
 *      tool surface; no hand-maintained drift).
 *   2. `docs/TOOL-CATALOG.md`               — standalone reference for
 *      humans browsing the repo.
 *   3. `manifest.json` builder                — pulls the same metadata
 *      to fill the DXT manifest's `tools` array.
 *
 * Invocation:
 *   node scripts/extract-tools.mjs                 # writes both outputs
 *   node scripts/extract-tools.mjs --print          # print Markdown only
 *   node scripts/extract-tools.mjs --json          # print JSON only
 *
 * Pre-req: `npm run build` (so dist/ is fresh).
 *
 * Dependency-free — only Node stdlib + dynamic import of the compiled
 * `@wootsup/yt-builder-mcp` package entry. Mirrors the dep-free
 * stance of `scripts/build-dxt.js`.
 */

import {
    existsSync,
    mkdirSync,
    readFileSync,
    writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, '..');
const DIST_INDEX = resolve(PKG_ROOT, 'dist', 'index.js');
// SKILL.md lives INSIDE the npm package (`packages/mcp/skills/`) so the
// `npm pack` tarball ships it — Round-1 audit C1 fix. The previous
// layout walked up to `<monorepo>/skills/` which left the tarball
// without a skill folder; install-skill failed in production.
const SKILL_PATH = resolve(PKG_ROOT, 'skills', 'yootheme-builder', 'SKILL.md');
const DOCS_PATH = resolve(PKG_ROOT, '..', '..', 'docs', 'TOOL-CATALOG.md');

const APPENDIX_BEGIN = '<!-- TOOL-CATALOG:BEGIN -->';
const APPENDIX_END = '<!-- TOOL-CATALOG:END -->';

function log(msg) {
    process.stdout.write(`[extract-tools] ${msg}\n`);
}

function fail(msg) {
    process.stderr.write(`[extract-tools] ERROR: ${msg}\n`);
    process.exit(1);
}

if (!existsSync(DIST_INDEX)) {
    fail(`dist/index.js missing — run \`npm run build\` first (looked at ${DIST_INDEX}).`);
}

const mod = await import(DIST_INDEX);
const { buildAllTools, RestClient } = mod;
if (typeof buildAllTools !== 'function') {
    fail('dist/index.js does not export buildAllTools.');
}
if (typeof RestClient !== 'function') {
    fail('dist/index.js does not export RestClient.');
}

const client = new RestClient({
    baseUrl: 'https://example.com',
    bearerToken: 'extract-tools-stub',
});
const tools = buildAllTools(client);

function describeAnnotations(a) {
    if (a === null || a === undefined || typeof a !== 'object') return 'read';
    const flags = [];
    if (a.readOnlyHint === true) flags.push('read');
    if (a.destructiveHint === true) flags.push('destructive');
    if (a.idempotentHint === true) flags.push('idempotent');
    if (a.openWorldHint === true) flags.push('openWorld');
    return flags.length === 0 ? 'mutating' : flags.join('+');
}

function listInputKeys(schema) {
    if (schema === null || schema === undefined || typeof schema !== 'object') {
        return [];
    }
    return Object.keys(schema).sort();
}

const records = tools
    .map((t) => ({
        name: String(t.name ?? ''),
        description: String(t.description ?? '').replace(/\s+/g, ' ').trim(),
        kind: describeAnnotations(t.annotations),
        inputKeys: listInputKeys(t.inputSchema),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

function renderMarkdownTable(rows) {
    const lines = [
        `**${rows.length} tools** — generated by \`scripts/extract-tools.mjs\` from the compiled \`buildAllTools()\` registry. Do not hand-edit this section; re-run \`npm run build && node scripts/extract-tools.mjs\` after changing tool definitions.`,
        '',
        '| Tool | Kind | Input keys | Description |',
        '| --- | --- | --- | --- |',
    ];
    for (const r of rows) {
        const keys =
            r.inputKeys.length === 0 ? '_(none)_' : '`' + r.inputKeys.join('`, `') + '`';
        // Escape pipe chars in the description so the table doesn't break.
        const desc = r.description.replace(/\|/g, '\\|');
        lines.push(`| \`${r.name}\` | ${r.kind} | ${keys} | ${desc} |`);
    }
    return lines.join('\n') + '\n';
}

const markdown = renderMarkdownTable(records);

const argv = process.argv.slice(2);
if (argv.includes('--print')) {
    process.stdout.write(markdown);
    process.exit(0);
}
if (argv.includes('--json')) {
    process.stdout.write(JSON.stringify(records, null, 2) + '\n');
    process.exit(0);
}

// 1. Write/update the SKILL.md appendix between sentinel markers.
if (existsSync(SKILL_PATH)) {
    const existing = readFileSync(SKILL_PATH, 'utf-8');
    const beginIdx = existing.indexOf(APPENDIX_BEGIN);
    const endIdx = existing.indexOf(APPENDIX_END);
    let next;
    if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
        next =
            existing.slice(0, beginIdx) +
            APPENDIX_BEGIN +
            '\n\n' +
            markdown +
            '\n' +
            APPENDIX_END +
            existing.slice(endIdx + APPENDIX_END.length);
    } else {
        next =
            existing.trimEnd() +
            '\n\n## Appendix: Tool Catalog (auto-generated)\n\n' +
            APPENDIX_BEGIN +
            '\n\n' +
            markdown +
            '\n' +
            APPENDIX_END +
            '\n';
    }
    writeFileSync(SKILL_PATH, next, 'utf-8');
    log(`updated ${SKILL_PATH}`);
} else {
    log(`SKIPPING SKILL.md — not found at ${SKILL_PATH}`);
}

// 2. Write the standalone docs catalog.
if (!existsSync(dirname(DOCS_PATH))) {
    mkdirSync(dirname(DOCS_PATH), { recursive: true });
}
const docsHeader = [
    '# YOOtheme Builder MCP — Tool Catalog',
    '',
    'Auto-generated reference. See `scripts/extract-tools.mjs` and the source',
    'in `packages/mcp/src/tools/`. The same content is also embedded in',
    '`skills/yootheme-builder/SKILL.md` between sentinel markers so AI clients',
    'pick it up via `install-skill`.',
    '',
    '',
].join('\n');
writeFileSync(DOCS_PATH, docsHeader + markdown, 'utf-8');
log(`wrote ${DOCS_PATH}`);

log(`done — ${records.length} tools catalogued`);
