/**
 * Auth / configuration loading for the MCP server.
 *
 * The MCP server reads two environment variables on startup:
 *
 *   YTB_MCP_SITE_URL      — base URL of the host CMS install (WordPress
 *                           OR Joomla), e.g. `https://example.com`.
 *                           The per-platform REST namespace
 *                           (`/wp-json/yt-builder-mcp/v1` for WP,
 *                           `/api/index.php/v1/yt-builder-mcp` for
 *                           Joomla) is appended internally based on
 *                           runtime platform detection.
 *   YTB_MCP_WP_URL        — DEPRECATED alias for YTB_MCP_SITE_URL,
 *                           kept for back-compat with pre-Wave 7
 *                           configurations. A non-fatal deprecation
 *                           notice is written to stderr when the
 *                           legacy var is used in non-test mode.
 *   YTB_MCP_BEARER_TOKEN  — the Bearer key generated by the plugin
 *                           Settings page (`wp-admin → YT Builder MCP`
 *                           on WordPress, `Components → YT Builder MCP`
 *                           on Joomla).
 *
 * `loadConfig()` throws `ConfigError` if either is missing, so the
 * server fails fast with a useful message rather than emitting cryptic
 * 401/Network errors deep in the request stack.
 *
 * @license MIT
 */

import { z } from 'zod';
import { ConfigError } from './errors.js';
import { synthesiseFromEnv } from './sites/env-bridge.js';
import { SiteRegistry } from './sites/registry.js';
import { SitesFile } from './sites/schema.js';
import { loadSitesFile } from './sites/store.js';

export interface ServerConfig {
    /** Base URL of the host-CMS install (no trailing slash). */
    readonly baseUrl: string;
    /** Bearer key. */
    readonly bearerToken: string;
    /** Network timeout (ms) for REST calls. */
    readonly timeoutMs: number;
    /**
     * Optional explicit platform hint from {@link ENV_PLATFORM}.
     * `undefined` lets the consumer rely on URL-shape detection.
     */
    readonly platformHint?: 'wordpress' | 'joomla';
}

export interface LoadConfigOptions {
    /** Allow the bearer-token to be empty (for health-only smoke tests). */
    readonly allowMissingToken?: boolean;
    /** Source of env vars (defaults to process.env). */
    readonly env?: NodeJS.ProcessEnv;
}

/**
 * Canonical env-var name for the host-CMS base URL (Wave 7+: covers
 * both WordPress and Joomla). Prefer this for all new configurations.
 */
export const ENV_SITE_URL = 'YTB_MCP_SITE_URL';
/**
 * Legacy env-var name kept for back-compat. Pre-Wave-7 configurations
 * (every release through v1.0.x) used `YTB_MCP_WP_URL`. New code should
 * use {@link ENV_SITE_URL}; this constant is retained so the wizard,
 * tests, and error hints can still reference the legacy name.
 */
export const ENV_WP_URL = 'YTB_MCP_WP_URL';
export const ENV_BEARER = 'YTB_MCP_BEARER_TOKEN';
export const ENV_TIMEOUT = 'YTB_MCP_TIMEOUT_MS';
export const ENV_TEST_MODE = 'YTB_MCP_TEST_MODE';
/**
 * Optional platform hint env var — `'wordpress'` or `'joomla'`. When
 * unset, the server auto-detects from the URL shape (cookbook §3.7.1):
 *   - URL contains `/wp-json/`        → wordpress
 *   - URL contains `/api/index.php/`  → joomla
 *   - origin-only URL                 → defaults to wordpress (back-compat)
 *
 * Set this to `'joomla'` when your YTB_MCP_SITE_URL is an origin-only
 * Joomla URL like `https://example.com/joomla`.
 */
export const ENV_PLATFORM = 'YTB_MCP_PLATFORM';
/**
 * W10 — canonical env-var name for the multi-site registry file. When
 * set, {@link loadRegistry} loads + validates the JSON at this path and
 * the legacy {@link ENV_SITE_URL} / {@link ENV_BEARER} pair is ignored.
 * When unset, the env-bridge falls back to building a one-site registry
 * from the legacy single-site pair.
 */
export const ENV_SITES_FILE = 'YTB_MCP_SITES_FILE';

const DEFAULT_TIMEOUT_MS = 15_000;

/**
 * Maximum accepted length for a Bearer token (defense-in-depth bound;
 * the real plugin keys are ~150-300 bytes, the 512 ceiling protects
 * against accidental file-pastes / log dumps / memory abuse).
 */
const BEARER_MAX_LEN = 512;

/**
 * Bearer-token format check — matches the plugin's `KeyService.php`
 * `PREFIX = ytb_live_` (and the planned `ytb_test_` future variant).
 * Token shape: `ytb_(live|test)_<payloadB64Url>.<sigB64Url>` where
 * base64url uses `[A-Za-z0-9_-]` (no dots inside the payload or sig).
 *
 * Round-1 audit I7 fix (2026-05-22): the earlier `.trim()` + empty-check
 * was not enough to catch the most common config mistakes — the leading
 * `Bearer ` prefix accidentally pasted into the env var, copy-paste
 * truncation (no `.` separator), or a totally wrong token style. We
 * fail-fast here so the client never sends a known-bad value upstream.
 */
const BEARER_FORMAT_SCHEMA = z
    .string()
    .max(
        BEARER_MAX_LEN,
        `Bearer too long (max ${String(BEARER_MAX_LEN)} chars). The env var YTB_MCP_BEARER_TOKEN seems to contain something other than a plain key — strip leading "Bearer " or paste only the key copied from wp-admin → "YT Builder MCP" → Settings.`,
    )
    .regex(
        /^ytb_(live|test)_[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/,
        'Bearer must match ytb_(live|test)_<payloadB64Url>.<sigB64Url> format (copy the key as shown in wp-admin → "YT Builder MCP" → Settings; do NOT prepend "Bearer ").',
    );

export function loadConfig(options: LoadConfigOptions = {}): ServerConfig {
    const env = options.env ?? process.env;
    // Wave 7: YTB_MCP_SITE_URL is canonical (covers both WP + Joomla);
    // YTB_MCP_WP_URL is retained as a deprecated back-compat alias.
    // Resolution order: SITE_URL wins; legacy WP_URL fallback emits a
    // soft deprecation note in non-test mode.
    const rawSiteUrl = (env[ENV_SITE_URL] ?? '').trim();
    const rawLegacyUrl = (env[ENV_WP_URL] ?? '').trim();
    const rawUrl = rawSiteUrl !== '' ? rawSiteUrl : rawLegacyUrl;
    // Soft deprecation notice — only when the loader is being used in
    // its real-server role (env defaulted to process.env). Programmatic
    // callers (tests, embedded uses) pass `options.env` explicitly and
    // are silently treated as opt-in to the legacy var.
    if (
        rawSiteUrl === ''
        && rawLegacyUrl !== ''
        && options.env === undefined
        && !isTestMode(env)
    ) {
        process.stderr.write(
            `[yt-builder-mcp] notice: ${ENV_WP_URL} is deprecated — ` +
                `set ${ENV_SITE_URL} instead (same value; covers WordPress + Joomla).\n`,
        );
    }
    const rawToken = (env[ENV_BEARER] ?? '').trim();
    const rawTimeout = (env[ENV_TIMEOUT] ?? '').trim();

    if (rawUrl === '') {
        throw new ConfigError(
            `Missing ${ENV_SITE_URL}. Set it to your CMS base URL ` +
                '(e.g. https://example.com — WordPress or Joomla). ' +
                'Run `yt-builder-mcp setup` to configure.',
        );
    }

    if (!options.allowMissingToken && rawToken === '') {
        throw new ConfigError(
            `Missing ${ENV_BEARER}. Generate a Bearer key in wp-admin → "YT Builder MCP" → ` +
                'Settings, then run `yt-builder-mcp setup`.',
        );
    }

    // I7-fix: enforce the Bearer-format contract before the client
    // makes any request. Empty token is allowed only via
    // `allowMissingToken` (the health-only smoke path); any other
    // non-empty value MUST match the plugin's KeyService format.
    if (rawToken !== '') {
        const parsed = BEARER_FORMAT_SCHEMA.safeParse(rawToken);
        if (!parsed.success) {
            const issueMsg = parsed.error.issues
                .map((iss) => iss.message)
                .join(' ');
            throw new ConfigError(
                `Invalid ${ENV_BEARER}: ${issueMsg}`,
            );
        }
    }

    let timeoutMs = DEFAULT_TIMEOUT_MS;
    if (rawTimeout !== '') {
        const parsed = Number.parseInt(rawTimeout, 10);
        if (Number.isFinite(parsed) && parsed > 0) {
            timeoutMs = parsed;
        }
    }

    const rawPlatform = (env[ENV_PLATFORM] ?? '').trim().toLowerCase();
    const platformHint: 'wordpress' | 'joomla' | undefined =
        rawPlatform === 'wordpress' || rawPlatform === 'joomla'
            ? rawPlatform
            : undefined;

    return {
        baseUrl: stripTrailingSlash(rawUrl),
        bearerToken: rawToken,
        timeoutMs,
        ...(platformHint !== undefined ? { platformHint } : {}),
    };
}

export function isTestMode(env: NodeJS.ProcessEnv = process.env): boolean {
    return (env[ENV_TEST_MODE] ?? '') === '1';
}

function stripTrailingSlash(url: string): string {
    return url.replace(/\/+$/, '');
}

/**
 * Options accepted by {@link loadRegistry}.
 */
export interface LoadRegistryOptions {
    /** Source of env vars (defaults to process.env). */
    readonly env?: NodeJS.ProcessEnv;
}

/**
 * W10 — canonical boot-time registry loader.
 *
 * Resolution order:
 *   1. **Sites file** — if {@link ENV_SITES_FILE} is set to a non-empty
 *      string, parse + validate the JSON at that path and wrap it in a
 *      {@link SiteRegistry}. Schema failures bubble up as
 *      `SitesFileError` (the store does not swallow them); the caller
 *      decides whether to fail-fast or fall back. Wave 10 chooses
 *      fail-fast — explicit file = explicit intent.
 *
 *   2. **Legacy env-bridge** — synthesise a one-site registry from the
 *      pre-W10 single-site env-vars ({@link ENV_SITE_URL} +
 *      {@link ENV_BEARER}, with {@link ENV_PLATFORM} as optional hint).
 *      Preserves the single-site UX for every customer who has not
 *      migrated to a sites.json yet.
 *
 *   3. **Hard fail** — neither configured. Surface a {@link ConfigError}
 *      with the three setup options so the operator knows exactly which
 *      knob to turn.
 *
 * This function replaces {@link loadConfig} on the main boot path.
 * `loadConfig` is intentionally retained for the test-mode fallback in
 * `index.ts` (`--test-mode` smoke probes) and for any embedded consumer
 * that still wants a flat `ServerConfig`.
 */
export async function loadRegistry(
    opts: LoadRegistryOptions = {},
): Promise<SiteRegistry> {
    const env = opts.env ?? process.env;

    // (1) sites file (preferred).
    const sitesFilePath = (env[ENV_SITES_FILE] ?? '').trim();
    if (sitesFilePath !== '') {
        // loadSitesFile handles both "file present" and "file absent"
        // (the latter returns an emptySitesFile). When the file is
        // empty (no sites), fall through to env-bridge instead of
        // booting with an empty registry — operators who set
        // SITES_FILE to a not-yet-populated path should still get the
        // legacy env-var ramp until they run `add-site`.
        const file = await loadSitesFile(sitesFilePath);
        if (file.sites.length > 0) {
            return new SiteRegistry(file);
        }
    }

    // (2) legacy env-bridge. The bridge already enforces URL/bearer
    // non-emptiness and platform-hint validity, but we re-validate the
    // full file shape through the W1 Zod schema before handing it to
    // the registry. Defense-in-depth: a future env-bridge change cannot
    // introduce a SitesFileT-shape regression that lands on the
    // registry path without first failing this gate.
    const synth = synthesiseFromEnv(env);
    if (synth !== null) {
        const parsed = SitesFile.safeParse(synth);
        if (!parsed.success) {
            const issues = parsed.error.issues
                .map((i) => `${i.path.join('.')}: ${i.message}`)
                .join('; ');
            throw new ConfigError(
                `Env-bridge synthesised an invalid sites file: ${issues}`,
            );
        }
        return new SiteRegistry(parsed.data);
    }

    // (3) fail-fast.
    throw new ConfigError(
        'No sites configured. Either: '
        + '(a) set YTB_MCP_SITES_FILE to your sites.json path, or '
        + '(b) set YTB_MCP_SITE_URL + YTB_MCP_BEARER_TOKEN for '
        + 'single-site mode, or '
        + '(c) run `npx -y @wootsup/yt-builder-mcp setup` interactively.',
    );
}
