/**
 * Auth / configuration loading for the MCP server.
 *
 * The MCP server reads two environment variables on startup:
 *
 *   YTB_MCP_WP_URL        — base URL of the WordPress install, e.g.
 *                           `https://example.com`. The REST namespace
 *                           `/wp-json/yt-builder-mcp/v1` is
 *                           appended internally.
 *   YTB_MCP_BEARER_TOKEN  — the Bearer key generated by the plugin
 *                           Settings page (`wp-admin → YT Builder MCP`).
 *
 * `loadConfig()` throws `ConfigError` if either is missing, so the
 * server fails fast with a useful message rather than emitting cryptic
 * 401/Network errors deep in the request stack.
 *
 * @license MIT
 */

import { z } from 'zod';
import { ConfigError } from './errors.js';

export interface ServerConfig {
    /** Base URL of the WordPress install (no trailing slash). */
    readonly baseUrl: string;
    /** Bearer key. */
    readonly bearerToken: string;
    /** Network timeout (ms) for REST calls. */
    readonly timeoutMs: number;
}

export interface LoadConfigOptions {
    /** Allow the bearer-token to be empty (for health-only smoke tests). */
    readonly allowMissingToken?: boolean;
    /** Source of env vars (defaults to process.env). */
    readonly env?: NodeJS.ProcessEnv;
}

export const ENV_WP_URL = 'YTB_MCP_WP_URL';
export const ENV_BEARER = 'YTB_MCP_BEARER_TOKEN';
export const ENV_TIMEOUT = 'YTB_MCP_TIMEOUT_MS';
export const ENV_TEST_MODE = 'YTB_MCP_TEST_MODE';

const DEFAULT_TIMEOUT_MS = 15_000;

/**
 * Maximum accepted length for a Bearer token (defense-in-depth bound;
 * the real plugin keys are ~150-300 bytes, the 512 ceiling protects
 * against accidental file-pastes / log dumps / memory abuse).
 */
const BEARER_MAX_LEN = 512;

/**
 * Bearer-token format check — matches the plugin's `KeyService.php`
 * `PREFIX = ytb_live_` (and the planned `ytb_test_` future variant).
 * Token shape: `ytb_(live|test)_<payloadB64Url>.<sigB64Url>` where
 * base64url uses `[A-Za-z0-9_-]` (no dots inside the payload or sig).
 *
 * Round-1 audit I7 fix (2026-05-22): the earlier `.trim()` + empty-check
 * was not enough to catch the most common config mistakes — the leading
 * `Bearer ` prefix accidentally pasted into the env var, copy-paste
 * truncation (no `.` separator), or a totally wrong token style. We
 * fail-fast here so the client never sends a known-bad value upstream.
 */
const BEARER_FORMAT_SCHEMA = z
    .string()
    .max(
        BEARER_MAX_LEN,
        `Bearer too long (max ${String(BEARER_MAX_LEN)} chars). The env var YTB_MCP_BEARER_TOKEN seems to contain something other than a plain key — strip leading "Bearer " or paste only the key copied from wp-admin → "YT Builder MCP" → Settings.`,
    )
    .regex(
        /^ytb_(live|test)_[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/,
        'Bearer must match ytb_(live|test)_<payloadB64Url>.<sigB64Url> format (copy the key as shown in wp-admin → "YT Builder MCP" → Settings; do NOT prepend "Bearer ").',
    );

export function loadConfig(options: LoadConfigOptions = {}): ServerConfig {
    const env = options.env ?? process.env;
    const rawUrl = (env[ENV_WP_URL] ?? '').trim();
    const rawToken = (env[ENV_BEARER] ?? '').trim();
    const rawTimeout = (env[ENV_TIMEOUT] ?? '').trim();

    if (rawUrl === '') {
        throw new ConfigError(
            `Missing ${ENV_WP_URL}. Set it to your WordPress base URL ` +
                '(e.g. https://example.com). Run `yt-builder-mcp setup` to configure.',
        );
    }

    if (!options.allowMissingToken && rawToken === '') {
        throw new ConfigError(
            `Missing ${ENV_BEARER}. Generate a Bearer key in wp-admin → "YT Builder MCP" → ` +
                'Settings, then run `yt-builder-mcp setup`.',
        );
    }

    // I7-fix: enforce the Bearer-format contract before the client
    // makes any request. Empty token is allowed only via
    // `allowMissingToken` (the health-only smoke path); any other
    // non-empty value MUST match the plugin's KeyService format.
    if (rawToken !== '') {
        const parsed = BEARER_FORMAT_SCHEMA.safeParse(rawToken);
        if (!parsed.success) {
            const issueMsg = parsed.error.issues
                .map((iss) => iss.message)
                .join(' ');
            throw new ConfigError(
                `Invalid ${ENV_BEARER}: ${issueMsg}`,
            );
        }
    }

    let timeoutMs = DEFAULT_TIMEOUT_MS;
    if (rawTimeout !== '') {
        const parsed = Number.parseInt(rawTimeout, 10);
        if (Number.isFinite(parsed) && parsed > 0) {
            timeoutMs = parsed;
        }
    }

    return {
        baseUrl: stripTrailingSlash(rawUrl),
        bearerToken: rawToken,
        timeoutMs,
    };
}

export function isTestMode(env: NodeJS.ProcessEnv = process.env): boolean {
    return (env[ENV_TEST_MODE] ?? '') === '1';
}

function stripTrailingSlash(url: string): string {
    return url.replace(/\/+$/, '');
}
